Add locked account banner
ORCID/orcid-angular pull request #1192
Opened 2021-10-05 23:15 UTC by leomendoza123

2021-10-05 23:38 UTC, DanielPalafox requested changes

2021-10-05 23:38 UTC, DanielPalafox commented on src/locale/properties/record/record.en.properties
> +record.accountLocked1=Your account has been locked
@ leomendoza123 Could you change the name of the properties to a more descriptive name like the other properties to have them homogenized

2021-10-06 00:23 UTC, DanielPalafox approved these changes

2021-10-06 00:40 UTC, merged

2021-10-06 00:41 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA][my-orcid] Signing into a locked account](https://trello.com/c/a0RZhXys/7597-qamy-orcid-signing-into-a-locked-account)