Fix/7704 qamy orcid new functionality for contributors in works not implemented
ORCID/orcid-angular pull request #1329
Opened 2021-11-05 22:07 UTC by DanielPalafox

2021-11-05 22:14 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA][my-orcid] New functionality for contributors in works not implemented](https://trello.com/c/t8fa5jir/7704-qamy-orcid-new-functionality-for-contributors-in-works-not-implemented)

2021-11-08 21:34 UTC, leomendoza123 commented on src/app/record/components/work/work.component.html
> +      <span i18n="#upperCase@@works.contributors"> Contributors </span>:
the `upperCase` will make `Contributors` be displayed as  `CONTRIBUTORS` on QA, is this what we want?

2021-11-08 21:44 UTC, leomendoza123 commented on src/app/record/components/work/work.component.html
> +      <span i18n="#upperCase@@works.contributors"> Contributors </span>:
We can remove this to avoid it been show in UPPER_CASE

2021-11-08 21:44 UTC, leomendoza123 requested changes
Just a small change

2021-11-08 22:22 UTC, leomendoza123 commented on src/app/record/components/work/work.component.html
> +      <span i18n="#upperCase@@works.contributors"> Contributors </span>:
Sorry Dani! Looking at the figma file 
![image](https://user-images.githubusercontent.com/2119626/140827578-83f87437-ae79-4b67-b3b1-a1c21c56b54a.png)
We DO need this to be upper case

2021-11-08 22:38 UTC, leomendoza123 approved these changes

2021-11-08 22:59 UTC, merged