fix: Add missing styles to contributors features
ORCID/orcid-angular pull request #1403
Opened 2021-12-01 22:44 UTC by DanielPalafox

2021-12-01 22:45 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA][my-orcid] New functionality for contributors in works not implemented](https://trello.com/c/t8fa5jir/7704-qamy-orcid-new-functionality-for-contributors-in-works-not-implemented)

2021-12-09 19:57 UTC, leomendoza123 approved these changes

2021-12-09 19:58 UTC, leomendoza123 commented on src/app/record/components/work/work.component.html
> +          <ng-container i18n="@@works.more">
This label is not using the right key

2021-12-09 20:00 UTC, leomendoza123 requested changes
Just a small translation missing

2021-12-13 17:45 UTC, DanielPalafox commented on src/app/record/components/work/work.component.html
> +          <ng-container i18n="@@works.more">
Done!

2021-12-13 17:47 UTC, amontenegro approved these changes

2021-12-13 17:56 UTC, merged