Feature/account settings security (Password update)
ORCID/orcid-angular pull request #1473
Opened 2022-02-02 20:46 UTC by leomendoza123

2022-02-03 00:55 UTC, DanielPalafox requested changes

2022-02-03 00:55 UTC, DanielPalafox commented on src/app/account-settings/components/settings-security/settings-security.component.html
> +<h2 class="orc-font-body col" i18n="@@account.defaults">Security</h2>
@leomendoza123 Can you fix this title

2022-02-03 00:55 UTC, DanielPalafox commented on src/app/account-settings/components/settings-security/settings-security.component.ts
> +  titleAccountPassword = $localize`:@@account.emailFrequency:Account password  `
@leomendoza123 Can you fix this localize property

2022-02-03 00:55 UTC, DanielPalafox commented on src/app/account-settings/components/settings-security-password/settings-security-password.component.html
> +  <div class="button-container" (click)="save()">
@leomendoza123 click event save it should go in the button not in the div

2022-02-03 00:55 UTC, DanielPalafox commented on src/app/account-settings/components/settings-security-password/settings-security-password.component.html
> +  <div *ngIf="success === true" class="error-container">
@leomendoza123 i18 property is missing here

2022-02-08 22:31 UTC, amontenegro approved these changes

2022-02-08 22:31 UTC, merged