Added additional fix for preferred identifiers and base url for wikidata
ORCID/orcid-angular pull request #1490
Opened 2022-02-09 22:23 UTC by Camelia-Orcid

2022-02-09 22:33 UTC, Camelia-Orcid commented
![](https://github.trello.services/images/mini-trello-icon.png) [ISNI org identifiers url is incorrect.](https://trello.com/c/dpjTdzYK/7898-isni-org-identifiers-url-is-incorrect)

2022-02-10 18:26 UTC, leomendoza123 commented on src/app/record/components/org-identifier/org-identifier.component.html
> +            *ngIf="isUrl(org.preferred)"
seems like `*ngIf="isUrl(org.preferred)"` will never be true, since is wrap with another  if `!isUrl(org.preferred)`

2022-02-10 18:27 UTC, leomendoza123 requested changes
Just a comment to check

2022-02-11 21:14 UTC, leomendoza123 approved these changes

2022-02-11 21:42 UTC, merged