set maximum password length
ORCID/orcid-angular pull request #1494
Opened 2022-02-11 14:00 UTC by auumgn

2022-02-11 20:30 UTC, leomendoza123 commented on src/app/sign-in/components/form-sign-in/form-sign-in.component.html
>    <mat-form-field appearance="outline" class="row password">
Looks like the dynamic class is still missing right?

2022-02-11 20:34 UTC, amontenegro requested changes

2022-02-11 20:34 UTC, amontenegro commented on src/app/register/components/form-password/form-password.component.html
> +      <div i18n="@@register.passwordLengthLimit">Between 8 and 64 characters long</div>
@auumgn as discussed, the upper limit should be 256 characters.
Thanks

2022-02-11 21:39 UTC, leomendoza123 approved these changes

2022-02-14 13:31 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Set a maximum length for passwords (3)](https://trello.com/c/oT9yFDcx/22-set-a-maximum-length-for-passwords-3)

2022-02-14 14:59 UTC, amontenegro approved these changes

2022-02-14 14:59 UTC, merged