Testing/url negtive testing cy scripts
ORCID/orcid-angular pull request #1545
Opened 2022-03-14 22:43 UTC by kprisAutomation

url negtive testing cy test cases and test data

2022-03-21 22:23 UTC, leomendoza123 requested changes

2022-03-21 22:23 UTC, leomendoza123 commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +    cy.wait(3000) //wait for language to refresh
We can avoid using the wait 
```suggestion
   cy.get('[lang="es"]') //wait for language to refresh
```

2022-03-21 22:23 UTC, leomendoza123 commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +    cy.wait(3000) //wait for language to refresh before Log out
We can avoid using the wait 
```suggestion
   cy.get('[lang="en"]') //wait for language to refresh
```

2022-03-21 23:45 UTC, kprisAutomation commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +      'https://api.qa.orcid.org/v3.0/' +
Done.

2022-03-21 23:46 UTC, kprisAutomation commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +    cy.cleanWebsites()
Done.

2022-03-21 23:46 UTC, kprisAutomation commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +  it('Arabic characters in title field are allowed', function () {
Done, moved these valid scenarios to the happy path script.

2022-03-22 00:03 UTC, kprisAutomation commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +    cy.wait(3000) //wait for language to refresh
Done

2022-03-22 00:03 UTC, kprisAutomation commented on cypress/integration/my-orcid/sidebar-add-websites-negative-testing.e2e.js
> +    cy.wait(3000) //wait for language to refresh before Log out
Done

2022-03-23 05:14 UTC, leomendoza123 approved these changes

2022-03-23 22:49 UTC, merged