feature: Update main peer review count to include number of review ac…
ORCID/orcid-angular pull request #1953
Opened 2023-05-12 05:11 UTC by DanielPalafox

…ross of publication/grants

2023-05-12 05:12 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change the main peer review item count to include number of review across number of journals/grants](https://trello.com/c/y76ygNP5/8603-change-the-main-peer-review-item-count-to-include-number-of-review-across-number-of-journals-grants)

2023-05-15 17:05 UTC, amontenegro requested changes

2023-05-15 17:05 UTC, amontenegro commented on src/app/cdk/panel/panels/panels.component.html
> +                <ng-container *ngIf="currentAmount === 1" i18n="@@peerReview.publicationsGrants"
@DanielPalafox here you are using the same key on both cases, shouldnt be a different case for singular than the one we use for plural? 

Looking at other parts of your PR, i think you use `peerReview.publicationsGrants` for plural and `peerReview.publicationGrant` for singular, right?

2023-05-16 20:58 UTC, amontenegro approved these changes

2023-05-16 20:58 UTC, merged