Take the providerId from signinData if the entityDisplayName not available
ORCID/orcid-angular pull request #2038
Opened 2023-08-10 12:27 UTC by Camelia-Orcid

2023-08-10 15:13 UTC, leomendoza123 approved these changes

2023-08-10 15:17 UTC, leomendoza123 requested changes
I am not super familiar with this session JSON. But is a bit confusing to me why we need to check if `this.entityDisplayName` is not falsy before re-assigning to a different value. 

Seems like your code would be equivalent to:

```
if (session.thirdPartyAuthData.entityDisplayName) { 
          this.entityDisplayName = this.signInData.providerId;
}
```

2023-08-10 15:27 UTC, Camelia-Orcid commented
We only want to set the this.entityDisplayName  to the providerId only if this.entityDisplayName = session.thirdPartyAuthData.entityDisplayName is nul or empty . Can you please review it.

2023-08-16 17:23 UTC, leomendoza123 approved these changes

2023-08-16 17:32 UTC, merged