Feature/register2
ORCID/orcid-angular pull request #2094
Opened 2023-11-23 22:29 UTC by leomendoza123

2023-11-23 22:34 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Updates to registration process](https://trello.com/c/cpW9gMnc/8896-updates-to-registration-process)

2023-11-27 22:26 UTC, amontenegro requested changes

2023-11-27 22:26 UTC, amontenegro commented on src/app/register2/components/top-bar-record-issues/top-bar-record-issues.component.html
> +<p>top-bar-record-issues works!</p>
@leomendoza123 can we remove this?

2023-11-27 22:26 UTC, amontenegro commented on src/app/register2/pages/register/register2.component.ts
> +  // openDialog(duplicateRecordsSearchResults: SearchResults): void {
@leomendoza123 can we remove this commented code?

2023-11-27 23:22 UTC, amontenegro approved these changes

2023-11-27 23:22 UTC, merged