fix: Update additional email message error
ORCID/orcid-angular pull request #2101
Opened 2023-12-04 22:59 UTC by DanielPalafox

2023-12-04 23:00 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] Apply dynamic email validation to additional email field in new register form](https://trello.com/c/EXyIW7p0/8951-qa-apply-dynamic-email-validation-to-additional-email-field-in-new-register-form)

2023-12-04 23:23 UTC, leomendoza123 requested changes

2023-12-04 23:23 UTC, leomendoza123 commented on src/app/register2/components/form-personal-additional-emails/form-personal-additional-emails.component.html
>          (additionalEmailsTouched &&
MatError will be show only if the control was touched AND it has an error. 

With the parentheses changes you are showing the error immediately if the pattern is not correct, right? I believe we want to wait until the user focuses out the control to show the error.

2023-12-05 20:20 UTC, amontenegro approved these changes

2023-12-05 20:21 UTC, merged