Add i18n keys
ORCID/orcid-angular pull request #2272
Opened 2024-05-30 21:31 UTC by amontenegro

2024-05-30 21:31 UTC, amontenegro commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update to Sign in with deactivated ORCID iD](https://trello.com/c/JFSwuS6b/9120-update-to-sign-in-with-deactivated-orcid-id)

2024-05-30 22:25 UTC, leomendoza123 approved these changes

2024-05-30 22:28 UTC, leomendoza123 requested changes
Please, remove html from inside the translation keys

2024-05-31 15:24 UTC, leomendoza123 approved these changes

2024-05-31 16:56 UTC, merged