fix institutional and social linking in oauth
ORCID/orcid-angular pull request #543
Opened 2020-09-17 23:37 UTC by DanielPalafox

https://trello.com/c/Jyda0iW5/6972-qa-institutional-and-social-linking-doesnt-work-as-part-of-oauth

2020-09-17 23:37 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] institutional and social linking doesn't work as part of OAuth](https://trello.com/c/Jyda0iW5/6972-qa-institutional-and-social-linking-doesnt-work-as-part-of-oauth)

2020-09-18 00:15 UTC, leomendoza123 requested changes

2020-09-21 16:41 UTC, DanielPalafox commented on src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
> +    if (this.signInLocal.params === undefined) {
Ok

2020-09-21 17:26 UTC, DanielPalafox commented on src/app/sign-in/components/form-sign-in/form-sign-in.component.ts
> +          this._user.getUserSession().subscribe(userSession => {
Ok

2020-09-21 20:56 UTC, leomendoza123 approved these changes

2020-09-21 21:37 UTC, closed without merging