fix OAuth request, the register is shown when the prompt login parame…
ORCID/orcid-angular pull request #603
Opened 2020-10-22 00:25 UTC by DanielPalafox

https://trello.com/c/qrsCFitY/7092-the-register-is-shown-on-promptlogin-requests-for-logged-in-users

2020-10-22 00:39 UTC, leomendoza123 requested changes
I see how this is better because it now matches the type definition. 
But looking into the code, I don't believe this is making any functional difference, can you please double-check it.

2020-10-22 00:47 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [The register is shown on prompt=login requests (for logged in users)](https://trello.com/c/qrsCFitY/7092-the-register-is-shown-on-promptlogin-requests-for-logged-in-users)

2020-10-22 03:47 UTC, DanielPalafox commented
Ohh my bad one commit is missing

2020-10-23 22:48 UTC, amontenegro approved these changes

2020-10-23 23:03 UTC, leomendoza123 approved these changes

2020-10-26 01:19 UTC, merged