fix removing parameters in institutional/social oauth
ORCID/orcid-angular pull request #631
Opened 2020-11-19 02:07 UTC by DanielPalafox

https://trello.com/c/EiZOE6b1/7138-oauth-urls-with-email-a-cancelled-account-link-registrations-will-remove-the-email-parameter-from-the-oauth-url

2020-11-19 04:37 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [Oauth URLs with email + a cancelled account-link registrations, will remove the email parameter from the Oauth URL](https://trello.com/c/EiZOE6b1/7138-oauth-urls-with-email-a-cancelled-account-link-registrations-will-remove-the-email-parameter-from-the-oauth-url)

2020-11-19 21:22 UTC, leomendoza123 requested changes
This change won't really prevent the OAuth parameters from been remove. This will only change the Oauth URL from having the original email to have the email given by the login facebook/google or institution.

That will be weird because if for instance, a university sends the user with a OAuth URL like:

`authorize?...clientId=App-1&email=Dani@universityX.org&name=daniel`

this might end up with a Url like 

`authorize?...clientId=App-1&email=daniel@gmail.org&name=Dani`


And this will be recorded in our GA data. 

A real solution is sending the shib/social data through the user session to fill the register, instead of using query parameters. But since this is a refactor that will affect multiple parts of the app we might rather wait to have more automation before going with this.

2021-02-15 17:32 UTC, amontenegro commented
@DanielPalafox @leomendoza123 lets revisit this, I will send you an invite for next week so we can discuss whats the better way to solve this problem.

2021-03-18 16:47 UTC, leomendoza123 commented
@DanielPalafox @amontenegro I propose closing this one in favor of https://github.com/ORCID/orcid-angular/pull/724

2021-03-18 18:21 UTC, closed without merging