Update zendesk autofill
ORCID/orcid-angular pull request #668
Opened 2021-01-14 12:33 UTC by auumgn

Re-opening to make minor changes to the autofill

2021-01-14 14:08 UTC, leomendoza123 requested changes
Great PR @auumgn!
I have added two comments about  it

2021-01-14 14:08 UTC, leomendoza123 commented on src/app/core/zendesk/zendesk.service.ts
> +            { id: '360039623413', prefill: { '*': uri || '' } },
URI is an array, we might cast it as a string with a `''+ uri`

2021-01-15 18:38 UTC, leomendoza123 approved these changes

2021-01-18 11:58 UTC, auumgn commented
![](https://github.trello.services/images/mini-trello-icon.png) [Auto populate Zendesk ticket OAuth errors (5)](https://trello.com/c/5NdhoT84/7084-auto-populate-zendesk-ticket-oauth-errors-5)

2021-01-19 17:32 UTC, merged