Fix AMENDED notifications aesthetics
ORCID/orcid-angular pull request #677
Opened 2021-02-02 18:12 UTC by leomendoza123

2021-02-02 18:12 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[QA] [new inbox] update required "made changes to your ORCID record"](https://trello.com/c/ozyv3c6Q/7234-qa-new-inbox-update-required-made-changes-to-your-orcid-record)

2021-02-03 14:47 UTC, amontenegro requested changes

2021-02-03 14:47 UTC, amontenegro commented on src/app/inbox/components/notification-your-record-amended/notification-your-record-amended.component.html
>    has updated the {{ getNotificationSectionUpdatedLabel(notification) }} section
@leomendoza123 all good with the PR! I'm just wondering why this section is not internationalized?

2021-02-03 17:06 UTC, DanielPalafox approved these changes

2021-02-03 18:45 UTC, amontenegro approved these changes

2021-02-03 18:45 UTC, merged