Expect/side bar orcid
ORCID/orcid-angular pull request #683
Opened 2021-02-08 18:47 UTC by leomendoza123

![screencapture-file-Users-leo-code-orcid-angular-cypress-reports-report-002-html-2021-02-08-12_40_34](https://user-images.githubusercontent.com/2119626/107266849-b6dc2f80-6a0b-11eb-98ff-0898e4890eb2.png)

2021-02-08 18:52 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[speedup] Sidebar (My ORCID/Component)](https://trello.com/c/q4FAfJAx/6936-speedup-sidebar-my-orcid-component)

2021-02-15 21:09 UTC, DanielPalafox requested changes

2021-02-15 21:09 UTC, DanielPalafox commented on cypress/integration/my-orcid-sidebar.e2e.js
> +    // cy.programmaticSignin('testUser')
@leomendoza123 I don't think these lines must be commented

2021-02-15 21:09 UTC, DanielPalafox commented on src/app/cdk/pannel/panel/panel.component.ts
> +      this._dialog.open(this.editModalComponent)
@leomendoza123 I thinks this should be different maxWidth is now missing

2021-02-16 13:22 UTC, closed without merging