add cypress names testing
ORCID/orcid-angular pull request #691
Opened 2021-02-20 01:55 UTC by DanielPalafox

2021-02-20 01:56 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [[speedup] Bio: Names modal (5)](https://trello.com/c/7mmo84WT/7216-speedup-bio-names-modal-5)

2021-02-22 13:44 UTC, leomendoza123 requested changes

2021-02-22 13:44 UTC, leomendoza123 commented on cypress/integration/my-orcid/my-orcid-top-bar.e2e.js
> +    before(() => {
Please do not delete the test description that we are not implementing. 
This is meant to be developed later by someone else.

2021-02-22 13:44 UTC, leomendoza123 commented on cypress/integration/my-orcid/my-orcid-top-bar.e2e.js
> +    before(() => {
like `change privacy` or `make changes and cancel`

2021-02-22 13:44 UTC, leomendoza123 commented on cypress/support/clean.commands.js
> +Cypress.Commands.add('cleanOtherNames', (url) => {
We are not using the URL parameter.
(I am deleting the other ones on my last PR)

2021-02-23 14:06 UTC, leomendoza123 approved these changes

2021-02-23 14:22 UTC, merged