Feature/g3 cejzax personal ids
ORCID/orcid-angular pull request #695
Opened 2021-02-23 19:56 UTC by leomendoza123

2021-02-24 16:30 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [[speedup] Bio: Person identifiers modal (3)](https://trello.com/c/Q8Z83GnY/7215-speedup-bio-person-identifiers-modal-3)

2021-02-24 18:40 UTC, DanielPalafox requested changes

2021-02-24 18:40 UTC, DanielPalafox commented on src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.html
> +    <div class="row"></div>
I don't think this is necessary

2021-02-24 18:40 UTC, DanielPalafox commented on src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.scss-theme.scss
> +  ::ng-deep .country-input-line {
Can you rename this or remove it, if it is not used

2021-02-24 18:40 UTC, DanielPalafox commented on src/app/cdk/side-bar/modals/modal-person-identifiers/modal-person-identifiers.component.ts
> +  personIdentifiersMap: { [key: string]: Assertion }
Could you remove this unused variable

2021-02-24 18:40 UTC, DanielPalafox commented on src/locale/properties/side-bar/side-bar.en.properties
> +side-bar.person-identifiers-description=Person identifiers are other identifiers that systems use to identify you, such as ResearcherID or Scopus Author ID. These identifiers can only be added by tru
Could you use camel case like in the other properties

2021-03-01 17:29 UTC, DanielPalafox approved these changes

2021-03-08 14:32 UTC, merged