fix expand activities buttons, my public afiliation error, etc
ORCID/orcid-angular pull request #796
Opened 2021-05-12 23:12 UTC by DanielPalafox

2021-05-12 23:20 UTC, leomendoza123 requested changes

2021-05-12 23:20 UTC, leomendoza123 commented on src/app/core/record-affiliations/record-affiliations.service.ts
> +    console.log(JSON.stringify(options))
log

2021-05-12 23:20 UTC, leomendoza123 commented on src/app/core/record-affiliations/record-affiliations.service.ts
> +  private getPublicAffiliationDetails(
Seems like nothing is calling this

2021-05-13 14:53 UTC, DanielPalafox commented on src/app/core/record-affiliations/record-affiliations.service.ts
> +  private getPublicAffiliationDetails(
You are right. I am gonna to remove it

2021-05-13 16:30 UTC, leomendoza123 approved these changes

2021-05-13 16:30 UTC, merged