boost is this you search
ORCID/orcid-angular pull request #913
Opened 2021-06-15 18:23 UTC by DanielPalafox

2021-06-15 18:27 UTC, DanielPalafox commented
![](https://github.trello.services/images/mini-trello-icon.png) [Boost records with affiliations in the "Could this be you?" modal](https://trello.com/c/XrHvdPDG/14-boost-records-with-affiliations-in-the-could-this-be-you-modal)

2021-06-15 20:04 UTC, leomendoza123 approved these changes

2021-06-15 20:05 UTC, leomendoza123 requested changes

2021-06-15 20:05 UTC, leomendoza123 commented on src/app/core/search/search.service.ts
> +    console.log(JSON.stringify(escapedParams))
PLeas review the console logs

2021-06-15 20:08 UTC, DanielPalafox commented on src/app/core/search/search.service.ts
> +    console.log(JSON.stringify(escapedParams))
Done @leomendoza123

2021-06-16 14:08 UTC, leomendoza123 approved these changes

2021-06-24 22:38 UTC, amontenegro commented
We are going to use the same components as the UI search, so, we can close this PR

2021-06-24 22:38 UTC, closed without merging