Feature/works modal
ORCID/orcid-angular pull request #940
Opened 2021-07-13 15:00 UTC by leomendoza123

2021-08-19 19:12 UTC, amontenegro requested changes

2021-08-19 19:12 UTC, amontenegro commented on src/app/record/components/funding-stack/funding-stack.component.html
> +      funding]="funding"
Make this a single line

2021-08-19 19:12 UTC, amontenegro commented on src/app/record/components/work-modal/work-modal.component.ts
> +    console.log('_____')
Do we need this console log?

2021-08-19 19:12 UTC, amontenegro commented on src/app/record/components/work-modal/work-modal.component.ts
> +      console.log(this.workForm.errors)
Do we need this? should we show an error to the user?

2021-08-19 21:51 UTC, leomendoza123 commented
Requested changes are ready

2021-08-24 21:28 UTC, DanielPalafox requested changes

2021-08-24 21:28 UTC, DanielPalafox commented on src/app/record/components/peer-reviews/peer-reviews.component.html
> +<ng-container *ngIf="peerReviews">
this file was deleted in a previous PR

2021-08-24 21:28 UTC, DanielPalafox commented on src/locale/properties/record/record.xx.properties
> +works.countryPublication=X
this property should go in the works.en.properties

2021-08-24 21:36 UTC, DanielPalafox approved these changes

2021-08-25 00:07 UTC, merged