Fix langauge guard
ORCID/orcid-angular pull request #979
Opened 2021-08-04 18:56 UTC by leomendoza123

2021-08-04 18:57 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [lang parameter doesn't work to update the site locale](https://trello.com/c/MwoPumam/7474-lang-parameter-doesnt-work-to-update-the-site-locale)

2021-08-04 18:57 UTC, leomendoza123 commented
![](https://github.trello.services/images/mini-trello-icon.png) [lang parameter doesn't work to update the site locale](https://trello.com/c/MwoPumam/7474-lang-parameter-doesnt-work-to-update-the-site-locale)

2021-08-05 21:22 UTC, DanielPalafox requested changes

2021-08-05 21:22 UTC, DanielPalafox commented on src/app/sign-in/pages/sign-in/sign-in.component.ts
> +    // this._route.queryParams.subscribe((params) => {
@leomendoza123 Could you remove this unused code

2021-08-09 22:06 UTC, merged